package test.generateAppModule.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 12 00:57:38 IST 2018
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void createRow();
}

