
package com.airtel.rs.proxy.dms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import com.airtel.rs.proxy.dms.type.Generic;
import com.airtel.rs.proxy.dms.type.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "GenericSoapPortType", targetNamespace = "urn:GenericSoap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface GenericSoapPortType {


    /**
     *
     * @param genericRequest
     * @return
     *     returns com.airtel.rs.proxy.dms.type.Generic
     */
    @WebMethod(operationName = "GenericSoapOperation", action = "urn:GenericSoap/GenericSoapOperation")
    @WebResult(name = "GenericResponse", targetNamespace = "http://www.oracle.com/UCM", partName = "GenericResponse")
    public Generic genericSoapOperation(@WebParam(name = "GenericRequest",
                                                  targetNamespace = "http://www.oracle.com/UCM",
                                                  partName = "GenericRequest") Generic genericRequest);

}
