package test.generateAppModule.model;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import test.generateAppModule.model.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 08 23:24:49 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for CountryEOView1.
     * @return CountryEOView1
     */
    public ViewObjectImpl getCountryEOView1() {
        return (ViewObjectImpl) findViewObject("CountryEOView1");
    }
    /**
     * custom method to create the row in the programmetically 
     */
    public void createRow(){
       ViewObjectImpl vo= getCountryEOView1();
       Row newRow= vo.createRow();
       newRow.setAttribute("CountryId", "ci");
       newRow.setAttribute("CountryName", "ICINDIA");
       newRow.setAttribute("RegionId", "4");
       vo.insertRow(newRow);
       getDBTransaction().commit();
    }

    /**
     * Container's getter for EmployeeEOView1.
     * @return EmployeeEOView1
     */
    public ViewObjectImpl getEmployeeEOView1() {
        return (ViewObjectImpl) findViewObject("EmployeeEOView1");
    }

    /**
     * Container's getter for EmployeeEOView2.
     * @return EmployeeEOView2
     */
    public ViewObjectImpl getEmployeeEOView2() {
        return (ViewObjectImpl) findViewObject("EmployeeEOView2");
    }

    /**
     * Container's getter for EmpManagerFkLink.
     * @return EmpManagerFkLink
     */
    public ViewLinkImpl getEmpManagerFkLink() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkLink");
    }

    /**
     * Container's getter for JobEOView1.
     * @return JobEOView1
     */
    public ViewObjectImpl getJobEOView1() {
        return (ViewObjectImpl) findViewObject("JobEOView1");
    }

    /**
     * Container's getter for EmployeeEOView3.
     * @return EmployeeEOView3
     */
    public ViewObjectImpl getEmployeeEOView3() {
        return (ViewObjectImpl) findViewObject("EmployeeEOView3");
    }

    /**
     * Container's getter for EmpJobFkLink.
     * @return EmpJobFkLink
     */
    public ViewLinkImpl getEmpJobFkLink() {
        return (ViewLinkImpl) findViewLink("EmpJobFkLink");
    }
}

