package test.generateAppModule.model;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 09 00:28:08 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountryEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CountryEODefImpl() {
    }
}

