package test.generateAppModule.model;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 09 00:28:10 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountryEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public CountryEOCollImpl() {
    }
}

